FROM node:18.14.2-alpine
# 14.18.0  | 14-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Exports
EXPOSE 80
#CMD [ "npm", "run", "start" ]
CMD [ "npm", "run", "start.dev" ]
